[build]
  command = "npm ci"
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"
  timeout = 120 # Timeout in seconds

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[dev]
  command = "netlify dev"
