[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  FIREBASE_PROJECT_ID = "your_firebase_project_id"
  FIREBASE_CLIENT_EMAIL = "your_firebase_client_email"
  FIREBASE_PRIVATE_KEY = "your_firebase_private_key"
  OPENAI_API_KEY = "your_openai_api_key"
